"""Inject the training-time system prompt into processed dataset files.

This module is the handoff between plain pairwise preference data and the final
training-ready files used by SFT / GRPO. It prepends the project's Chinese judge
system prompt so every record has the same conversation structure expected by
``src.data.rl_dataset`` and ``src.model.inference``.
"""

import json
from pathlib import Path

from src.model.chat_prompt_chinese import SYSTEM_PROMPT_CHAT_CHINESE as SYSTEM_PROMPT

# --- Configuration ---
# Input files
TRAIN_FILE_IN = Path("data/processed/train.jsonl")
TEST_FILE_IN = Path("data/processed/test.jsonl")

# Output files
TRAIN_FILE_OUT = Path("data/processed/train_with_sys.jsonl")
TEST_FILE_OUT = Path("data/processed/test_with_sys.jsonl")
# --- End Configuration ---


def inject_system_prompt(input_path: str, output_path: str):
    """
    Add a leading system message to every record when one is missing.

    Input:
    - ``input_path``: JSONL generated by ``src.data.split`` or another dataset builder

    Output:
    - ``output_path``: JSONL with ``*_with_sys`` naming convention

    The original file is left untouched so both prompt variants can coexist.
    """
    input_path = Path(input_path)
    output_path = Path(output_path)
    print(f"Processing '{input_path}' -> '{output_path}'...")
    
    # Check if the input file exists before proceeding
    if not input_path.exists():
        print(f"  [Warning] Input file not found: '{input_path}'. Skipping.")
        return 0

    records_processed = 0
    records_skipped = 0
    with open(input_path, "r", encoding="utf-8") as fin, \
         open(output_path, "w", encoding="utf-8") as fout:
        for i, line in enumerate(fin):
            try:
                record = json.loads(line)
            except json.JSONDecodeError:
                print(f"  [Warning] Line {i+1}: Skipping malformed JSON in '{input_path}'.")
                continue

            # Ensure 'context_messages' exists and is a list
            messages = record.get("context_messages", [])
            if not isinstance(messages, list):
                 print(f"  [Warning] Line {i+1}: 'context_messages' is not a list. Skipping record.")
                 records_skipped += 1
                 continue

            # Prepend system prompt only if the first message is not already 'system'
            if not messages or messages[0].get("role") != "system":
                messages.insert(0, {"role": "system", "content": SYSTEM_PROMPT})
            
            record["context_messages"] = messages
            
            fout.write(json.dumps(record, ensure_ascii=False) + "\n")
            records_processed += 1
            
    print(f"  [Info] Done. Processed {records_processed} records.")
    if records_skipped > 0:
        print(f"  [Info] Skipped {records_skipped} records due to formatting issues.")
    return records_processed


if __name__ == "__main__":
    print("--- Starting Data Preprocessing: Inject System Prompt ---")

    TRAIN_FILE_OUT.parent.mkdir(parents=True, exist_ok=True)
    inject_system_prompt(TRAIN_FILE_IN, TRAIN_FILE_OUT)
    inject_system_prompt(TEST_FILE_IN, TEST_FILE_OUT)
    
    print("\n--- Preprocessing Complete ---")
    print(f"New training file created: {TRAIN_FILE_OUT}")
    print(f"New testing file created:  {TEST_FILE_OUT}")
    print("\nReminder: Please update your RL training entry to point to the new '_with_sys.jsonl' files.")
